project:
  type: website
  output-dir: .  # Set the output directory to the root


website:
  title: "Optimization of Ember Electricity Generation Data"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    include-in-header:
      - text: |
          <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    self-contained: true
    code-fold: show
    toc: true
    toc-float:
      collapsed: false
      smooth-scroll: true
    theme: default
    number-sections: false

execute:
  echo: true
  warning: false
  message: false
  fig-align: center
  fig-height: 6
  fig-width: 8
  progress: true
  verbose: true
