project:
  type: website

website:
  title: "Testing prediction models"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format: 
  html:
    embed-resources: true
    self-contained: true
    code-fold: true
    toc: true
    toc-depth: 5
    toc-float:
      collapsed: true
      smooth-scroll: true
    theme: default
    number-sections: false
execute:
  echo: true
  cache: true
  warning: false
  message: false
  fig-align: center
  progress: true
  verbose: false

editor: visual

